
trigger: none

pool:
  vmImage: ubuntu-latest
stages:
  - stage: deploy
    jobs:
      - deployment: Test
        environment: Test
        strategy:
         runOnce:
            deploy:
               steps:
                 - checkout: self
                 - script: echo "This is my first deployment job demo"

